spring:
  application:
    name: monitoring
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  sql:
    init:
      encoding:
  server:
    error:
      include-message: never
  mvc:
    favicon:
      enabled=false:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
    whitelabel:
      enabled: false