spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/monitoring
    username: park
    password: gupark
  thymeleaf:
    check-template-location: false


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.park.monitoring.model
  configuration:
    map-underscore-to-camel-case: true