spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.2.61:3306/monitoring
    username: park
    password: gupark
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health, info, metrics