#DB관련
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.2.66:3306/monitoring
    username: park
    password: gupark
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml

#에러페이지
server:
  error:
    include-exception: true



management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health, info, metrics