spring:
  application:
    name: monitoring
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  sql:
    init:
      encoding:
  server:
    error:
      include-message: never
  mvc:
    favicon:
      enabled=false:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /help
  api-docs:
    groups:
      enabled : true
    enabled: true
    path: /api-docs
  version: 1.0.0
server:
    whitelabel:
      enabled: false