spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.2.61:3306/monitoring
    username: park
    password: gupark

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.park.monitoring.model
  configuration:
    map-underscore-to-camel-case: true

server:
  error:
    include-exception: true